#---
- hosts: local
  become: yes
  tasks:
    - include_tasks: tasks/firewall.yml
    - include_tasks: tasks/user.yml
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/wordpress.yml
    - include_tasks: tasks/backup.yml
