version: '3.8'

services:

  wordpress:
    image: wordpress
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  ansible:
    image: willhallonline/ansible:2.16.4-ubuntu-22.04
    # environment:
    #   - PWD=${PWD}
    volumes:
      - ${PWD}/ansible:/tmp/ansible
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: /bin/bash -c "ansible-playbook $PWD/ansible/playbooks/site.yml -i ansible/inventory/hosts.ini"

  backup:
   image: alpine:latest
   volumes:
      - backup_data:/backups
   entrypoint: /bin/sh -c "while true; do sleep 1d; /backup.sh; done"

volumes:
  wordpress:
  db:
  backup_data: